## SupportVectorClassification - MoviesData

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv("Movie_classification.csv", header=0)

In [3]:
data.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  Trailer_views 3D_available  Time_taken  \
0            7.995           7.94         527367          YES      109.60   
1            7.470           7.44         494055           NO      146.64   
2            7.515           7.44         547051           NO      147.88   
3            7.020           8.26         516279          YES      185.36   
4            7.070           8.26         531448           NO      176.48   

   Twitter_hastags     Genre  Avg_age_actors  Num_multiplex  Collection  \
0          223.840  Thriller              23            494       48000   
1          243.456     Drama              42            462       43200   
2         2022.400    Comedy              38            458       69400   
3          225.344     Drama              45            472       66800   
4          225.792     Drama              55            395       72400   

   Start_Tech_Oscar  
0                 1  
1                 0  
2                 1  
3                 1  
4                 1

In [4]:
data.describe().transpose()

count           mean           std          min  \
Marketing expense    506.0      92.270471    172.030902      20.1264   
Production expense   506.0      77.273557     13.720706      55.9200   
Multiplex coverage   506.0       0.445305      0.115878       0.1290   
Budget               506.0   34911.144022   3903.038232   19781.3550   
Movie_length         506.0     142.074901     28.148861      76.4000   
Lead_ Actor_Rating   506.0       8.014002      1.054266       3.8400   
Lead_Actress_rating  506.0       8.185613      1.054290       4.0350   
Director_rating      506.0       8.019664      1.059899       3.8400   
Producer_rating      506.0       8.190514      1.049601       4.0300   
Critic_rating        506.0       7.810870      0.659699       6.6000   
Trailer_views        506.0  449860.715415  68917.763145  212912.0000   
Time_taken           494.0     157.391498     31.295161       0.0000   
Twitter_hastags      506.0     260.832095    104.779133     201.1520   
Avg_age_actors       506.0      39.181818     12.513697       3.0000   
Num_multiplex        506.0     545.043478    106.332889     333.0000   
Collection           506.0   45057.707510  18364.351764   10000.0000   
Start_Tech_Oscar     506.0       0.545455      0.498422       0.0000   

                              25%          50%           75%         max  
Marketing expense        21.64090      25.1302      93.54165    1799.524  
Production expense       65.38000      74.3800      91.20000     110.480  
Multiplex coverage        0.37600       0.4620       0.55100       0.615  
Budget                32693.95250   34488.2175   36793.54250   48772.900  
Movie_length            118.52500     151.0000     167.57500     173.500  
Lead_ Actor_Rating        7.31625       8.3075       8.86500       9.435  
Lead_Actress_rating       7.50375       8.4950       9.03000       9.540  
Director_rating           7.29625       8.3125       8.88375       9.425  
Producer_rating           7.50750       8.4650       9.03000       9.635  
Critic_rating             7.20000       7.9600       8.26000       9.400  
Trailer_views        409128.00000  462460.0000  500247.50000  567784.000  
Time_taken              132.30000     160.0000     181.89000     217.520  
Twitter_hastags         223.79600     254.4000     283.41600    2022.400  
Avg_age_actors           28.00000      39.0000      50.00000      60.000  
Num_multiplex           465.00000     535.5000     614.75000     868.000  
Collection            34050.00000   42400.0000   50000.00000  100000.000  
Start_Tech_Oscar          0.00000       1.0000       1.00000       1.000

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Marketing expense    506 non-null    float64
 1   Production expense   506 non-null    float64
 2   Multiplex coverage   506 non-null    float64
 3   Budget               506 non-null    float64
 4   Movie_length         506 non-null    float64
 5   Lead_ Actor_Rating   506 non-null    float64
 6   Lead_Actress_rating  506 non-null    float64
 7   Director_rating      506 non-null    float64
 8   Producer_rating      506 non-null    float64
 9   Critic_rating        506 non-null    float64
 10  Trailer_views        506 non-null    int64  
 11  3D_available         506 non-null    object 
 12  Time_taken           494 non-null    float64
 13  Twitter_hastags      506 non-null    float64
 14  Genre                506 non-null    object 
 15  Avg_age_actors       506 non-null    int

### Missing Value Imputation

In [6]:
data.fillna(value = data['Time_taken'].mean(), inplace=True)

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Marketing expense    506 non-null    float64
 1   Production expense   506 non-null    float64
 2   Multiplex coverage   506 non-null    float64
 3   Budget               506 non-null    float64
 4   Movie_length         506 non-null    float64
 5   Lead_ Actor_Rating   506 non-null    float64
 6   Lead_Actress_rating  506 non-null    float64
 7   Director_rating      506 non-null    float64
 8   Producer_rating      506 non-null    float64
 9   Critic_rating        506 non-null    float64
 10  Trailer_views        506 non-null    int64  
 11  3D_available         506 non-null    object 
 12  Time_taken           506 non-null    float64
 13  Twitter_hastags      506 non-null    float64
 14  Genre                506 non-null    object 
 15  Avg_age_actors       506 non-null    int

### Dummy Variable Creation

In [8]:
data.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  Trailer_views 3D_available  Time_taken  \
0            7.995           7.94         527367          YES      109.60   
1            7.470           7.44         494055           NO      146.64   
2            7.515           7.44         547051           NO      147.88   
3            7.020           8.26         516279          YES      185.36   
4            7.070           8.26         531448           NO      176.48   

   Twitter_hastags     Genre  Avg_age_actors  Num_multiplex  Collection  \
0          223.840  Thriller              23            494       48000   
1          243.456     Drama              42            462       43200   
2         2022.400    Comedy              38            458       69400   
3          225.344     Drama              45            472       66800   
4          225.792     Drama              55            395       72400   

   Start_Tech_Oscar  
0                 1  
1                 0  
2                 1  
3                 1  
4                 1

In [9]:
data = pd.get_dummies(data=data, columns=["3D_available","Genre"], drop_first=True)

In [10]:
data.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  ...  Time_taken  Twitter_hastags  \
0            7.995           7.94  ...      109.60          223.840   
1            7.470           7.44  ...      146.64          243.456   
2            7.515           7.44  ...      147.88         2022.400   
3            7.020           8.26  ...      185.36          225.344   
4            7.070           8.26  ...      176.48          225.792   

   Avg_age_actors  Num_multiplex  Collection  Start_Tech_Oscar  \
0              23            494       48000                 1   
1              42            462       43200                 0   
2              38            458       69400                 1   
3              45            472       66800                 1   
4              55            395       72400                 1   

   3D_available_YES  Genre_Comedy  Genre_Drama  Genre_Thriller  
0                 1             0            0               1  
1                 0             0            1               0  
2                 0             1            0               0  
3                 1             0            1               0  
4                 0             0            1               0  

[5 rows x 21 columns]

### Splitting Data into X and y

In [11]:
X = data.loc[:,data.columns != 'Start_Tech_Oscar']
y = data.loc[:, data.columns == 'Start_Tech_Oscar']

In [12]:
print(X.shape)
print(y.shape)

(506, 20)
(506, 1)


### Train-Test Split

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2,random_state=0)

In [14]:
X_train.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
220            27.1618               67.40               0.493  38612.805   
71             23.1752               76.62               0.587  33113.355   
240            22.2658               64.86               0.572  38312.835   
6              21.7658               70.74               0.476  33396.660   
417           538.8120               91.20               0.321  29463.720   

     Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
220         162.0               8.485                8.640            8.485   
71           91.0               7.280                7.400            7.290   
240         127.8               6.755                6.935            6.800   
6           140.1               7.065                7.265            7.150   
417         162.6               9.135                9.305            9.095   

     Producer_rating  Critic_rating  Trailer_views  Time_taken  \
220            8.670           8.52         480270      174.68   
71             7.455           8.16         491978      200.68   
240            6.840           8.68         470107      204.80   
6              7.400           8.96         459241      139.16   
417            9.165           6.96         302776      172.16   

     Twitter_hastags  Avg_age_actors  Num_multiplex  Collection  \
220          224.272              23            536       53400   
71           263.472              46            400       43400   
240          224.320              24            387       54000   
6            243.664              41            522       45800   
417          301.664              60            589       20800   

     3D_available_YES  Genre_Comedy  Genre_Drama  Genre_Thriller  
220                 0             0            0               1  
71                  0             0            0               0  
240                 1             1            0               0  
6                   1             0            0               1  
417                 1             0            0               0

In [15]:
X_test.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
329            21.3448               61.48               0.540  35179.815   
371           204.6460               91.20               0.369  34529.880   
219            22.2850               82.78               0.450  35402.015   
403           516.0340               91.20               0.307  29713.695   
78             21.1292               80.66               0.563  34618.760   

     Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
329          90.7               7.320                7.460            7.275   
371         173.5               9.310                9.525            9.320   
219         165.9               8.175                8.375            8.315   
403         169.5               9.125                9.310            9.060   
78          127.2               7.330                7.500            7.450   

     Producer_rating  Critic_rating  Trailer_views  Time_taken  \
329            7.515           8.62         483051  111.040000   
371            9.505           7.96         454281  196.000000   
219            8.405           8.72         451935  123.200000   
403            9.100           6.96         384237  157.391498   
78             7.690           8.26         447528  176.480000   

     Twitter_hastags  Avg_age_actors  Num_multiplex  Collection  \
329          283.616              53            452       45200   
371          268.000              25            609      100000   
219          263.680              21            561       46000   
403          301.328              40            677       16600   
78           303.392              53            377       42400   

     3D_available_YES  Genre_Comedy  Genre_Drama  Genre_Thriller  
329                 0             1            0               0  
371                 1             1            0               0  
219                 1             1            0               0  
403                 1             0            0               1  
78                  1             0            1               0

In [16]:
y_train.head()

Start_Tech_Oscar
220                 1
71                  1
240                 1
6                   0
417                 1

In [17]:
y_test.head()

Start_Tech_Oscar
329                 0
371                 1
219                 0
403                 0
78                  0

In [18]:
print(X_train.shape)
print(y_train.shape)
print('---------')
print(X_test.shape)
print(y_test.shape)

(404, 20)
(404, 1)
---------
(102, 20)
(102, 1)


### Standardizing Data

In [19]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [21]:
X_train_std = scaler.fit_transform(X_train)
X_test_std = scaler.transform(X_test)

In [23]:
#X_train_std

In [25]:
#X_test_std

### Training SVM
https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html

In [27]:
from sklearn.svm import SVC
svc = SVC(kernel='linear', C=100)
svc.fit(X_train_std, y_train)

/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=100, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

### Predict values using trained model

In [30]:
y_train_pred = svc.predict(X_train_std)
y_test_pred = svc.predict(X_test_std)

In [31]:
y_test_pred

array([1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0])

### Model Performance

In [32]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [37]:
confusion_matrix(y_test, y_test_pred)

array([[25, 19],
       [25, 33]])

In [38]:
accuracy_score(y_test, y_test_pred)

0.5686274509803921

In [39]:
svc.n_support_

array([144, 146], dtype=int32)

### Grid Search

In [42]:
from sklearn.model_selection import GridSearchCV

In [43]:
params = {
    'C' : (0.001,0.005,0.01,0.05, 0.1, 0.5, 1, 5, 10, 50,100,500,1000)
}

In [44]:
svc_1 = SVC(kernel='linear')

In [46]:
svc_grid_linear = GridSearchCV(
                            svc_1,
                            params,
                            n_jobs=1,
                            cv=10,
                            verbose=1,
                            scoring='accuracy'
                            )

In [47]:
svc_grid_linear.fit(X_train_std, y_train)

Fitting 10 folds for each of 13 candidates, totalling 130 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d ar

/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example usin

/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example usin

/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example usin

GridSearchCV(cv=10, error_score='raise-deprecating',
             estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='auto_deprecated', kernel='linear',
                           max_iter=-1, probability=False, random_state=None,
                           shrinking=True, tol=0.001, verbose=False),
             iid='warn', n_jobs=1,
             param_grid={'C': (0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 5, 10, 50,
                               100, 500, 1000)},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='accuracy', verbose=1)

In [49]:
svc_grid_linear.best_params_

{'C': 0.5}

In [64]:
svc_grid_linear_best = svc_grid_linear.best_estimator_

In [65]:
y_train_pred_best = svc_grid_linear_best.predict(X_train_std)

In [66]:
confusion_matrix(y_train, y_train_pred_best)

array([[119,  67],
       [ 60, 158]])

In [69]:
accuracy_score(y_train, y_train_pred) * 100

69.3069306930693

In [72]:
y_test_pred_best = svc_grid_linear_best.predict(X_test_std)

In [73]:
confusion_matrix(y_test, y_test_pred_best)

array([[26, 18],
       [23, 35]])

In [74]:
accuracy_score(y_test, y_test_pred_best) * 100

59.80392156862745

### Polynomial

In [75]:
svc_grid_poly = SVC(kernel='poly', degree=3, C=0.1)
svc_grid_poly.fit(X_train_std, y_train)

/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=0.1, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='poly', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [76]:
y_train_poly_best = svc_grid_poly.predict(X_train_std)
y_test_poly_best = svc_grid_poly.predict(X_test_std)

In [77]:
accuracy_score(y_test, y_test_poly_best) * 100

57.84313725490197

In [78]:
svc_grid_poly.n_support_

array([185, 198], dtype=int32)

### Radial

In [79]:
svc_grid_radial = SVC(kernel='rbf', gamma=0.5, C=10)
svc_grid_radial.fit(X_train_std, y_train)

/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.5, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [80]:
y_train_radial_best = svc_grid_radial.predict(X_train_std)
y_test_radial_best = svc_grid_radial.predict(X_test_std)

In [82]:
accuracy_score(y_test, y_test_radial_best) * 100

61.76470588235294

In [83]:
svc_grid_radial.n_support_

array([186, 218], dtype=int32)

### Radial Grid

In [84]:
params = {
    'C' : (0.01,0.05, 0.1, 0.5, 1, 5, 10, 50),
    'gamma' : (0.001, 0.01, 0.1, 0.5, 1)
}

In [85]:
svc_2 = SVC(kernel='rbf')

In [86]:
svc_grid_rbf = GridSearchCV(
                        svc_2,
                        params,
                        n_jobs=1,
                        cv=3,
                        verbose=1,
                        scoring='accuracy'
                        )

In [87]:
svc_grid_rbf.fit(X_train_std, y_train)

Fitting 3 folds for each of 40 candidates, totalling 120 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d ar

/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example usin

/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example usin

GridSearchCV(cv=3, error_score='raise-deprecating',
             estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='auto_deprecated', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='warn', n_jobs=1,
             param_grid={'C': (0.01, 0.05, 0.1, 0.5, 1, 5, 10, 50),
                         'gamma': (0.001, 0.01, 0.1, 0.5, 1)},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='accuracy', verbose=1)

In [88]:
svc_grid_rbf.best_params_

{'C': 50, 'gamma': 0.001}

In [89]:
svc_grid_rbf_radial = svc_grid_rbf.best_estimator_

In [90]:
y_test_pred_radial = svc_grid_rbf_radial.predict(X_test_std)

In [91]:
accuracy_score(y_test, y_test_pred_radial) * 100

61.76470588235294

In [92]:
svc_grid_rbf_radial.n_support_

array([162, 166], dtype=int32)