## Numpy Examples

In [2]:
import numpy as np

In [3]:
my_list = [1,2,3]

In [4]:
type(my_list)

list

In [6]:
my_arr = np.array(my_list)
my_arr
type(my_arr)

numpy.ndarray

In [9]:
my_matrix = [[1,2,3], [4,5,6], [7,8,9]]
print(my_matrix)
print(type(my_matrix))

my_numpy_matrix = np.array(my_matrix)
print(my_numpy_matrix)
print(type(my_numpy_matrix))

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
<class 'list'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [10]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros(5, int)

array([0, 0, 0, 0, 0])

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [19]:
np.linspace(1,5)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [20]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [22]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [23]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
np.random.rand(5)

array([0.56195966, 0.02467638, 0.73483139, 0.16888465, 0.75053914])

In [33]:
np.random.rand(1)

array([0.44627719])

In [34]:
np.random.rand(1)

array([0.58816811])

In [35]:
np.random.rand(1,10)

array([[0.1135843 , 0.21871998, 0.2761376 , 0.48730878, 0.58445511,
        0.12376913, 0.01181735, 0.212453  , 0.85547383, 0.11819276]])

In [36]:
np.random.rand(1,10, 2)

array([[[0.4058867 , 0.32164517],
        [0.08942513, 0.12729847],
        [0.62725464, 0.56096348],
        [0.93168448, 0.96214109],
        [0.96776084, 0.89874006],
        [0.44153629, 0.57653066],
        [0.23016935, 0.49071019],
        [0.98357446, 0.45866627],
        [0.77562776, 0.83846465],
        [0.48788746, 0.06291846]]])

In [37]:
np.random.rand(2,10)

array([[0.23545246, 0.03718787, 0.11772125, 0.89495833, 0.118941  ,
        0.10759501, 0.15972476, 0.01062293, 0.57553831, 0.27785432],
       [0.20942209, 0.0417184 , 0.49196005, 0.38438968, 0.3137671 ,
        0.63168964, 0.09315428, 0.36996863, 0.84525353, 0.92602395]])

In [38]:
np.random.randn(1)

array([0.20599797])

In [39]:
np.random.randn(10)

array([-1.57254111,  0.51458582,  0.95965606, -3.06061625, -1.2124526 ,
       -0.8727879 ,  1.69665905,  0.21878328, -0.30996798, -1.78613582])

In [40]:
np.random.randn(10,2)

array([[ 0.32047016, -0.42676963],
       [-0.45233201,  0.0849073 ],
       [ 0.00888756,  0.76247495],
       [ 0.58832497, -1.12437944],
       [ 0.92919047, -0.01804942],
       [-0.0469386 , -0.11894958],
       [-0.58066415, -1.17401428],
       [ 2.25198265, -0.14882429],
       [ 1.65567733,  0.8989683 ],
       [ 2.12286508,  0.51730555]])

In [41]:
np.random.randint(1)

0

In [45]:
np.random.randint(1,100)

55

In [46]:
np.random.randint(1,100)

73

In [47]:
np.random.randint(2,100)

63

In [51]:
np.random.randint(1,100, 5)

array([28, 67, 24, 79, 34])

In [50]:
np.random.randint(1,100, (4,5))

array([[39, 90, 51, 36, 44],
       [47, 98, 49, 18, 93],
       [40, 13, 43, 36, 78],
       [13, 57, 97, 43, 85]])

In [55]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [58]:
arr = np.arange(0,25)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [62]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [64]:
ranarr = np.random.randint(0,101,10)
ranarr

array([ 1, 87, 29, 37,  1, 63, 59, 20, 32, 75])

In [66]:
ranarr.max()

87

In [67]:
ranarr.min()

1

In [69]:
ranarr.mean()

40.4

In [70]:
ranarr.argmax()

1

In [71]:
ranarr.argmin()

0

In [73]:
ranarr.argsort()

array([0, 4, 7, 2, 8, 3, 6, 5, 9, 1])

In [75]:
ranarr.dtype

dtype('int64')

In [78]:
arr.shape

(25,)

In [79]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [80]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [81]:
arr.shape

(25,)

In [83]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [85]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [87]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
arr[8]

8

In [90]:
arr[1:5]

array([1, 2, 3, 4])

In [91]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [92]:
arr[:5]

array([0, 1, 2, 3, 4])

In [93]:
arr[5:]

array([5, 6, 7, 8, 9])

In [94]:
arr[0:5] = 100

In [95]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [96]:
arr = np.arange(0,11)

In [98]:
slice_of_arr = arr[0:5]
slice_of_arr

array([0, 1, 2, 3, 4])

In [99]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99])

In [101]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [104]:
arr_2d = np.array([[5,10,15], [20,35,46], [78,32,39]])
print(type(arr_2d))
print(arr_2d)

<class 'numpy.ndarray'>
[[ 5 10 15]
 [20 35 46]
 [78 32 39]]


In [105]:
arr_2d.shape

(3, 3)

In [106]:
arr_2d[0]

array([ 5, 10, 15])

In [107]:
arr_2d[2]

array([78, 32, 39])

In [108]:
arr_2d[0][1]

10

In [109]:
arr_2d[1][2]

46

In [110]:
arr_2d[1,2]

46

In [111]:
arr_2d

array([[ 5, 10, 15],
       [20, 35, 46],
       [78, 32, 39]])

In [119]:
arr_2d[:2,1:]

array([[10, 15],
       [35, 46]])

In [121]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [122]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [123]:
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [124]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [125]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [126]:
import numpy as np
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])

total_rolls_over_two = dice_rolls[dice_rolls > 2]

In [127]:
total_rolls_over_two

array([3, 5, 5, 5, 4, 4, 5, 3, 4, 5, 4, 6, 6, 3, 6, 3, 5, 6, 5])

In [128]:
len(total_rolls_over_two)

19

In [133]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [134]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [135]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [136]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [137]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [138]:
arr / arr

<ipython-input-138-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [139]:
1 / 0

ZeroDivisionError: division by zero

In [140]:
1 / arr[0]

<ipython-input-140-9e44f9282194>:1: RuntimeWarning: divide by zero encountered in long_scalars
  1 / arr[0]


inf

In [141]:
1 / arr

<ipython-input-141-e66ae8057bc3>:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [142]:
np.sqrt(4)

2.0

In [143]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [144]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [145]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [146]:
np.log(arr)

<ipython-input-146-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [147]:
arr.sum()

45

In [148]:
arr.mean()

4.5

In [149]:
arr.min()

0

In [150]:
arr.max()

9

In [151]:
arr.std()

2.8722813232690143

In [152]:
arr.var()

8.25

In [156]:
arr2d = np.arange(0,25).reshape(5,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [157]:
arr2d.sum()

300

In [158]:
arr2d.sum(axis=1) # Columns

array([ 10,  35,  60,  85, 110])

In [159]:
arr2d.sum(axis=0) # Rows

array([50, 55, 60, 65, 70])